# load data
```{r}
dir.create("06.SLRMP")
geo = readRDS("01.datatidy/GEO_afterBatch.rds")
tcga = readRDS("01.datatidy/crcData.rds")
scMMR = readRDS("01.datatidy/sc_MMR.rds")
rmps_score = readRDS("05.scSeq/rmp_enrich_meta.rds")
sc_Ann = data.table::fread("01.datatidy/scAnn.txt", header = F)
colnames(sc_Ann) = c("symbol", "ensg")
sc_Ann$ensg = stringr::str_split(sc_Ann$ensg, "_", simplify = T)[,1]
```

```{r}
convertRownames <- function(seu_object, scAnn) {
  new_rownames <- sc_Ann$symbol[match(rownames(seu_object), sc_Ann$ensg)]
  rownames(seu_object@assays$RNA@counts) <- new_rownames
  rownames(seu_object@assays$RNA@data) <- new_rownames
  return(seu_object)
}
scMMR = convertRownames(seu_object = scMMR, scAnn = sc_Ann)
```

# Tidy data
```{r}
rmps_score = split(rmps_score, rmps_score$PatientTypeID)
TidySc = function(subdat){
  # subdat = rmps_score$C103_T
  subexp = data.frame(scMMR@assays$RNA@counts[,subdat$sampleID])
  subexp = apply(subexp, 1, sum)
  subdat = split(subdat, subdat$clFull)
  E1 = mean(subdat$`cE01 (Stem/TA-like)`$rmps_score)
  E3 = mean(subdat$`cE03 (Stem/TA-like prolif)`$rmps_score)
  out = list(exp = subexp, SErmps = data.frame(E1 = E1, E3 = E3))
  return(out)
}
scTidy = lapply(rmps_score, TidySc)
saveRDS(scTidy, file = "06.SLRMP/scTidy.rds")
```

```{r}
sc_exp = lapply(scTidy, function(x){x = x$exp})
sc_exp = do.call(cbind, sc_exp)

scSEscore = lapply(scTidy, function(x){x = x$SErmps})
scSEscore = do.call(rbind, scSEscore)
scSEscore$Type = stringr::str_split(row.names(scSEscore), "_", simplify = T)[,2]
scSEscore = subset(scSEscore, Type != "N")

samGene = intersect(row.names(sc_exp), row.names(tcga$exp))
samGene = intersect(samGene, row.names(geo$exp))

sc_exp = sc_exp[samGene, row.names(scSEscore)]
geo_exp = geo$exp[samGene,]
tcga_exp = tcga$exp[samGene,]
```

```{r}
sc_exp = apply(sc_exp, 2, rank)
geo_exp = apply(geo_exp, 2, rank)
tcga_exp = apply(tcga_exp, 2, rank)
write.csv(sc_exp, file = "06.SLRMP/model/sc_exp.csv")
write.csv(geo_exp, file = "06.SLRMP/model/geo_exp.csv")
write.csv(tcga_exp, file = "06.SLRMP/model/tcga_exp.csv")
write.csv(scSEscore, file = "06.SLRMP/model/scSEscore.csv")
```

